version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_bot
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: bot_database
    volumes:
      - ./bot_data:/app/data # Пример для сохранения данных бота вне контейнера

  db:
    image: postgres:15
    container_name: bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
